version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"