os:
  - linux
language: node_js
node_js:
  - 'lts/*'
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
install:
  - npm install -g @angular/cli
  - cd ./wowup-electron && npm install
jobs:
  include:
    - stage: test
      if: os = linux
      script:
        - ng lint
        - ng test --watch=false --include='src/locales.spec.ts'
    #- stage: build
      # if: os = linux AND type = pull_request AND branch IN (develop) 
      # script:
        # - ng test --watch=false --include='src/locales.spec.ts'
